# Generated by Django 4.0.4 on 2022-05-22 07:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Mobile')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('gender', models.CharField(blank=True, choices=[(None, 'Choose your gender'), ('male', 'male'), ('female', 'female'), ('custom', 'custom'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=50, verbose_name='gender')),
                ('student_number', models.IntegerField(blank=True, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.path')),
            ],
        ),
    ]
