# Generated by Django 4.0.4 on 2022-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='register/profil.jpg', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
